#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import sys


path = '/home/{}/.cache'.format(os.environ['USER'])
brifile = os.path.join(path, 'brightness')
cmd = 'xrandr --output {screen} --brightness {brightness}'
brinow = 0

try:
    brinow = open(brifile).read().strip('\n')
except:
    pass

brinxt = float(sys.argv[1]) + float(brinow)
brinxt = 0 if brinxt < 0 else brinxt
brinxt = 1 if brinxt > 1 else brinxt


os.system(cmd.format(screen='eDP-1', brightness=brinxt))
open(brifile, 'w').write(str(brinxt))
