#!/usr/bin/env bash

# xx=$( xrandr | grep ' conn' | awk '{print $1}' )
# echo $xx
# 
# scr1=$( echo $xx | awk '{print $1}' )
# scr2=$( echo $xx | awk '{print $2}' )
# 
# xrandr --output $scr1 --right-of $scr2 --auto
# xrandr --output $scr2 --primary
# 
# sleep 1
# 
# i3 restart

xrandr --auto
sleep 1
xrandr --output DP-1 --right-of DP-3
sleep 1
xrandr --output VGA-0 --right-of DP-1
sleep 1
xrandr --output DP-3 --primary
sleep 1
i3 restart
