#!/usr/bin/env bash

# xrandr --auto
# sleep 1
# xrandr --output DP-0 --right-of VGA-0
# sleep 1
# xrandr --output DP-1 --right-of DP-0
# sleep 1
# xrandr --output VGA-0 --primary
# sleep 1
# i3 restart
# sleep 1
# startConky

# wallpaper 0
# sleep 1

i3-msg 'workspace 1' -q
i3-msg 'workspace 6' -q
i3-msg 'workspace 2' -q
i3-msg 'workspace 10' -q
i3-msg 'workspace 3' -q
i3-msg 'focus child' -q
i3-msg 'move container to workspace 1' -q
i3-msg 'workspace 1' -q
# sleep 1
#sllogin

[[ `netctl status enp0s25-CHANG | grep -i 'active: active'` ]] || sudo netctl restart enp0s25-CHANG
