#!/usr/bin/env python3
import requests
import sys
from bs4 import BeautifulSoup as bs

url = 'https://www.ip2location.com/demo'

try:
    r = requests.post(url, params={
        'ipAddress': sys.argv[1],
    })
except IndexError:
    print('IP address is required.')
    exit(1)

table = bs(r.text, features='html5lib').find('table')

result = ''
for tr in table.find_all('tr')[1:]:
    result += format(tr.find('th').find('strong').text, '<30')
    result += tr.find('td').text.strip() + '\n'

print(result)
print
