#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import sys
import subprocess
import imghdr

true_judge = False

path = os.path.realpath('.')
try:
    expath = sys.argv[1]
    if expath == '--true':
        true_judge = True
    else:
        if expath[0] == '/' or expath[0] == '~':
            path = expath
        else:
            path = os.path.join(path, expath)
        path = os.path.abspath(path)
except IndexError:
    pass

picq = ['jpg', 'png']
piclist = []

try:
    for r, d, f in os.walk(path):
        for file in f:
            if true_judge:
                if imghdr.what(os.path.join(r, file)) != None:
                    piclist.append(os.path.join(r, file))
            else:
                if file[-3:] in picq:
                    piclist.append(os.path.join(r, file))
except FileNotFoundError:
    print('Directory not found ' + path)
except PermissionError:
    print('Permission Denied ' + path)

cmd = ['feh', '-dF']

for pic in piclist:
    if os.path.isfile(pic):
        cmd.append(pic)
if len(cmd) == 2:
    print('no picture')
else:
    subprocess.call(cmd)

