#!/usr/bin/env bash

sudo netctl restart enp0s25-Home && sleep 1
while (true); do
    curl 'http://222.24.215.2/srun_portal_pc.php' --data 'action=login&ac_id=14&url=&username=2017302344&password=zxcvbnm1234567' --silent > /dev/null
    [[ $? == 0 ]] || sleep 1 && break
done
