#!/usr/bin/env python3

from pymouse import PyMouse
import os
import i3ipc

i3 = i3ipc.Connection()
mouse = PyMouse()

div = 5


os.system('killall conky')
os.system('/usr/bin/conky -c $HOME/.conky/conkyleft')
os.system('/usr/bin/conky -c $HOME/.conky/conkyright')

tree = i3.get_tree()

focused = tree.find_focused()
conkyl = tree.find_named('conkyl')[0]
conkyr = tree.find_named('conkyr')[0]

os.system('sleep 0.2')
conkyl.command('move left 540')
os.system('sleep 0.2')
conkyr.command('move right 540')
os.system('sleep 0.2')
focused.command('focus')

flagl = False
flagr = False


while True:
    size = mouse.screen_size()[0]
    x, y = mouse.position()
    focused = i3.get_tree().find_focused()

    if x < div:
        if not flagl:
            for i in range(10):
                conkyl.command('move right 54')
                os.system('sleep 0.01')
            flagl = True
    if x > size - div:
        if not flagr:
            for i in range(10):
                conkyr.command('move left 54')
                os.system('sleep 0.01')
            flagr = True
    if x > 543:
        if flagl:
            for i in range(10):
                conkyl.command('move left 54')
                os.system('sleep 0.01')
            flagl = False
    if x < size - 543:
        if flagr:
            for i in range(10):
                conkyr.command('move right 54')
                os.system('sleep 0.01')
            flagr = False
        focused.command('focus')

    os.system('sleep 0.2')
