#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import os
import random
from os import system
from os import path

default_wallp = '{}/Pictures/WallP'.format(os.environ['HOME'])
try:
    wallp = open('{}/.cache/wallpaper_path'.format(os.environ['HOME']), 'r').read().strip('\n')
except:
    wallp = default_wallp

socdir = path.split(path.relpath(__file__))[0]

pic = os.listdir(wallp)
siz = len(pic)


def get_path(xxx):
    if xxx[0] == '/' or xxx == '~':
        ret = xxx
    else:
        ret = os.path.join(os.path.abspath('.'), xxx)
    return os.path.abspath(ret)


def cp2wallp(_f):
    if _f[-3:] not in ['png', 'jpg']:
        return False, ""
    _f = get_path(_f)
    cnt = 1
    while True:
        file_name = 'P{}'.format(format(str(cnt), '0>3') + _f[-4:])
        full_name = os.path.join(default_wallp, file_name)
        if os.path.exists(full_name):
            cnt += 1
            continue
        os.system('cp "{}" "{}"'.format(_f, full_name))
        print('copy "{}" to "{}" as "{}"'.format(_f, default_wallp, file_name))
        return True, file_name


def usage():
    print("""
Usage: wallpaper [OPTION]... [FILE]

    num                 set the numth image after current as wallpaper
    -d                  remove current from hub.
    -r                  randomly select an image from hub as wallpaper
    -a file1 file2 ...  add file1, file2... to hub
    -s file             add file to hub and set it as wallpaper
    --dir path          set wallpaper path
    """)
    # TODO: Complete this function
    pass


now = 0
try:
    now = open('/home/angel/.cache/wallpaper', 'r').read().strip('\n')
    now = int(now)
except (FileNotFoundError, ValueError):
    now = 0

nxt, add = now, 0
try:
    add = int(sys.argv[1])
except IndexError:
    usage()
    exit(0)
except ValueError:
    if sys.argv[1] == '-d':
        system('rm -f "{}"'.format(path.join(wallp, pic[now])))
        print('remove "{}" from "{}"'.format(path.join(wallp, pic[now]), wallp))
        add = 1
    elif sys.argv[1] == '-r':
        add = random.randint(0, siz + 1)
    elif sys.argv[1] == '-a':
        for picture in sys.argv[2:]:
            cp2wallp(picture)
        exit(0)
    elif sys.argv[1] == '-s':
        try:
            flg, f = cp2wallp(sys.argv[2])
            if not flg:
                print('"{}" is not a valid picture.')
                exit(-1)
            os.system('feh --bg-fill "{}"'.format(path.join(default_wallp, f)))
            exit(0)
        except IndexError:
            print('No picture selected')
    elif sys.argv[1] == '--dir':
        try:
            os.system('echo {} > $HOME/.cache/wallpaper_path'.format(get_path(sys.argv[2])))
            exit(0)
        except IndexError:
            print('path is required.')
            usage()
            exit(-1)
    else:
        print('Invalid options\n')
        usage()
        exit(-1)
nxt = (now + add) % siz

system('feh --bg-fill "{}"'.format(path.join(wallp, pic[nxt])))
open('/home/angel/.cache/wallpaper', 'w').write(str(nxt))


